algoritmo "Exemplo 01"
// Função :Exemplo de Condicional Simples
// Autor : Ana Clara Cordeiro
// Data : 26/07/2022
// Seção de Declarações 
var
idade:inteiro

inicio
escreval("Entre com a idade: ")
leia(idade)
se idade>=18 entao
   escreval("PODE PASSAR!")
   escreval("VERDADIRO")
senao
   escreval("NÃO PODE PASSAR!")
   escreval("FALSO")
fimse
escreval ("ACABOU.....")
fimalgoritmo
