algoritmo "1-exibir tabuada"
// Função :
// Autor :Ana Clara Cordeiro Lima
// Data : 30/08/2022
// Seção de Declarações 
var
contador,numero,resultado: inteiro

inicio

escreval("Digite um número:")
leia(numero)

para contador de 1 ate 10 faca
  //resultado <- numero * contador
  escreval(numero," * ",contador," = ",resultado * contador)
fimpara
  
// Seção de Comandos 
fimalgoritmo
