algoritmo "2-fatorial"
// Função :
// Autor :Ana Clara Cordeiro Lima
// Data : 30/08/2022
// Seção de Declarações 
var
contador,numero,resultado: inteiro

inicio
escreval("Digite um número:")
leia(numero)

se (numero = 0)
    escreval("resultado => 1")
Senao
   para contador de 1 ate numero faca
   resultado <- numero * contador
   fimpara
fimse
escreval("resultado => 1")
// Seção de Comandos 
fimalgoritmo
