algoritmo "Algoritmo CalculaValorTotal"
// Função : Calular valor total
// Autor : Ana Clara Cordeiro Lima
// Data : 26/04/2022
// Seção de Declarações 
var
qtde,valor,VT:real

inicio
escreval("Quantidade de peças")
leia(qtde)
escreval("Valor das peças")
leia(valor)
//FIM DOS DADOS DE ENTRADA
//PROCESSAMENTO
VT <- qtde*valor
//FIM PROCESSAMENTO

//DADOS DE SAIDA
escreval ("O valor total é: ",VT)





// Seção de Comandos 
fimalgoritmo
