algoritmo "2"
// Função :
// Autor :
// Data : 20/09/2022
// Seção de Declarações 
var
nota1,nota2,soma: inteiro
media: real
inicio
escreval("Digite a primeira nota: ")
leia(nota1)
escreval("Digite a segunda nota: ")
leia(nota2)
soma <- nota1 + nota2
escreval("A soma das notas dão: ",soma)
media <- soma / 2
escreval("A média das notas dão: ",media)



// Seção de Comandos 
fimalgoritmo
